{% set name = "Office365-REST-Python-Client" %}
{% set version = "2.5.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vgrem/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: c5d4fbf80d1f53b752360746bbaf6f176ace1c8f82feff27683578cbfa23d562

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - requests
    - msal
    - pytz
    - typing-extensions >=4.0.0

test:
  imports:
    - office365
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vgrem/Office365-REST-Python-Client
  summary: Microsoft 365 & Microsoft Graph Library for Python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/vgrem/Office365-REST-Python-Client/blob/master/README.md
  dev_url: https://github.com/vgrem/Office365-REST-Python-Client

extra:
  recipe-maintainers:
    - marcelotrevisani
    - rxm7706
