{% set name = "office365-rest-python-client" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Office365-REST-Python-Client-{{ version }}.tar.gz
  sha256: 9087dcd9d7231437afc66b98dbef2ce21f589c61d2e82f941955cff4a53cd3ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - msal
    - pytz

test:
  imports:
    - office365
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vgrem/Office365-REST-Python-Client
  summary: Microsoft 365 & Microsoft Graph Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
